{
   "jobs" : {
      "hook_needupdate" : {
         "if" : "${{ github.ref == 'refs/heads/master' }}",
         "runs-on" : "ubuntu-latest",
         "steps" : [
            {
               "uses" : "actions/checkout@v2",
               "with" : {
                  "token" : "${{ secrets.GH_ACCESS_TOKEN }}"
               }
            },
            {
               "run" : "git config --global user.email \u0022temp@github.test\u0022"
            },
            {
               "run" : "git config --global user.name \u0022GitHub Actions\u0022"
            },
            {
               "run" : "make updatebyhook"
            },
            {
               "run" : "git diff-index --quiet HEAD --cached || git commit -m updatebyhook"
            },
            {
               "run" : "git push origin \u002B`git rev-parse HEAD`:refs/heads/nightly"
            }
         ]
      }
   },
   "name" : "hook",
   "on" : {
      "repository_dispatch" : {
         "types" : [
            "needupdate"
         ]
      }
   }
}
